FROM python:alpine3.20

# Use high numbered unencrypted port.
EXPOSE 5000/tcp

# Put files in an app folder.
WORKDIR /app

COPY requirements.txt .

# Copy dependencies into image.
# TODO: Consider pulling requirements inside build stage's venv and COPY packages in dockerfile. Adds visibility of packages, but adds complexity, need to weigh benefits.
RUN pip install -r requirements.txt

COPY app.py .

# Specify the command to run on container start
CMD [ "python", "./app.py" ]